/** Rough flag emoji for common manufacturing countries (fallback 🌍). */
const NAME_TO_FLAG: Record<string, string> = {
  bangladesh: '🇧🇩',
  cambodia: '🇰🇭',
  china: '🇨🇳',
  vietnam: '🇻🇳',
  india: '🇮🇳',
  indonesia: '🇮🇩',
  pakistan: '🇵🇰',
  'sri lanka': '🇱🇰',
  philippines: '🇵🇭',
  thailand: '🇹🇭',
  malaysia: '🇲🇾',
  mexico: '🇲🇽',
  guatemala: '🇬🇹',
  honduras: '🇭🇳',
  brazil: '🇧🇷',
  colombia: '🇨🇴',
  peru: '🇵🇪',
  argentina: '🇦🇷',
  morocco: '🇲🇦',
  tunisia: '🇹🇳',
  egypt: '🇪🇬',
  jordan: '🇯🇴',
  ethiopia: '🇪🇹',
  kenya: '🇰🇪',
  'south korea': '🇰🇷',
  korea: '🇰🇷',
  taiwan: '🇹🇼',
  japan: '🇯🇵',
  portugal: '🇵🇹',
  spain: '🇪🇸',
  italy: '🇮🇹',
  romania: '🇷🇴',
  bulgaria: '🇧🇬',
  poland: '🇵🇱',
  ukraine: '🇺🇦',
  moldova: '🇲🇩',
  'united states': '🇺🇸',
  usa: '🇺🇸',
  'united kingdom': '🇬🇧',
  uk: '🇬🇧',
  germany: '🇩🇪',
  france: '🇫🇷',
  netherlands: '🇳🇱',
  belgium: '🇧🇪',
  ireland: '🇮🇪',
  turkey: '🇹🇷',
  greece: '🇬🇷',
  myanmar: '🇲🇲',
  laos: '🇱🇦',
  'el salvador': '🇸🇻',
  nicaragua: '🇳🇮',
  haiti: '🇭🇹',
  'dominican republic': '🇩🇴',
  lesotho: '🇱🇸',
  madagascar: '🇲🇬',
};

export function flagEmojiForCountry(name: string): string {
  const k = name.trim().toLowerCase();
  return NAME_TO_FLAG[k] ?? '🌍';
}
